Attempting to add exampled to CI/CD

diff --git a/.github/workflows/trivy-docker-test.yml b/.github/workflows/trivy-docker-test.yml
--- a/.github/workflows/trivy-docker-test.yml
+++ b/.github/workflows/trivy-docker-test.yml
@@ -10,21 +10,28 @@ permissions:
 jobs:
   trivy-check:
     runs-on: ubuntu-latest
-    steps:
-      - name: Run Trivy on image
-        id: trivy
-        uses: aquasecurity/trivy-action@master
-        with:
-          image-ref: 'ghcr.io/pi3dra/ci-decret/cve-2016-3714:latest'
-          format: 'json'
-          output: 'trivy-results.json'
+    strategy:
+      matrix:
+        cve:
+          - cve-2016-3714
+          - cve-2014-0160
+          - cve-2020-7247
+          - cve-2023-22809
 
-      - name: Check for CVE-2016-3714
+    steps:
+      - name: Run Trivy scan for ${{ matrix.cve }}
+        uses: aquasecurity/trivy-action@master
+        id: trivy
+        with:
+          image-ref: ghcr.io/pi3dra/ci-decret/${{ matrix.cve }}:latest
+          format: json
+          output: trivy-results.json
+
+      - name: Check for ${{ matrix.cve }} in scan results
         run: |
-          echo "Looking for CVE-2016-3714 in Trivy results..."
-          if ! grep -q "CVE-2016-3714" trivy-results.json; then
-            echo "CVE-2016-3714 not found! Failing the job."
+          if ! grep -q "${{ matrix.cve }}" trivy-results.json; then
+            echo "${{ matrix.cve }} not found! Failing the job."
             exit 1
           else
-            echo "CVE-2016-3714 found as expected."
+            echo "${{ matrix.cve }} found as expected."
           fi
